import { Router, type IRouter } from "express";
import healthRouter from "./health";
import profileRouter from "./profile";
import coursesRouter from "./courses";
import plannerRouter from "./planner";
import gpaRouter from "./gpa";
import transferRouter from "./transfer";
import policiesRouter from "./policies";
import dashboardRouter from "./dashboard";
import openaiRouter from "./openai";
import articulationRouter from "./articulation";
import graduationPathsRouter from "./graduation-paths";
import evaluationRouter from "./evaluation";
import sectionsRouter from "./sections";
import voiceRouter from "./voice";
import professorsRouter from "./professors";
import feedbackRouter from "./feedback";
import requirementsRouter from "./requirements";

const router: IRouter = Router();

router.use(healthRouter);
router.use(profileRouter);
router.use(coursesRouter);
router.use(plannerRouter);
router.use(gpaRouter);
router.use(transferRouter);
router.use(policiesRouter);
router.use(dashboardRouter);
router.use(openaiRouter);
router.use(articulationRouter);
router.use(graduationPathsRouter);
router.use(evaluationRouter);
router.use(sectionsRouter);
router.use(voiceRouter);
router.use(professorsRouter);
router.use(feedbackRouter);
router.use(requirementsRouter);

export default router;
